export const GET_GOODS_LOADING_SAGA = "SAGA::GET_GOODS_LOADING_SAGA";
export const GOODS_GET_SAGA = "SAGA::GOODS_GET_SAGA";
export const GOODS_ERROR_SAGA = "SAGA::GOODS_ERROR_SAGA";
export const ERROR_FIREBASE_SAGA = "SAGA::ERROR_FIREBASE_SAGA";
export const CHENGE_AUTH_USER_SAGA = "SAGA::CHENGE_AUTH_USER_SAGA";
export const CHENGE_LOADING_SAGA = "SAGA::CHENGE_LOADING_SAGA";
