export const GET_GOODS_REQUEST = "GOODS::GET_GOODS_REQUEST";
export const SIZE_GOODS_ACTION = "GOODS::SIZE_GOODS_ACTION"
export const PRICE_ACTION = "GOODS::PRICE_ACTION"
export const SEARCH_ACTION = "GOODS::SEARCH_ACTION"
export const GOODS_PRODUCT_ACTION = "GOODS::GOODS_PRODUCT_ACTION"
export const GOODS_SEARCH_GOODS_ACTION = "GOODS::GOODS_SEARCH_GOODS_ACTION"
export const CHENGE_PAGE_ACTION = "GOODS::CHENGE_PAGE_ACTION"